import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans =  DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin",]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
        <head>
            <link
                href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&display=swap"
                rel="stylesheet"
            />
        </head>
        <body
            className={`${dmSans.variable} antialiased`}
        >
            {children}
        </body>
    </html>
  );
}
